# Generated by Django 5.2.12 on 2026-03-14 06:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('SHELF', 'Shelf'), ('RACK', 'Rack'), ('ZONE', 'Zone'), ('FLOOR', 'Floor'), ('DOCK', 'Dock (Receiving/Shipping)'), ('OTHER', 'Other')], default='SHELF', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('warehouse', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code e.g., WH1, MAIN', max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InventoryOperation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, help_text='Auto-generated reference e.g., REC-00001', max_length=50, unique=True)),
                ('op_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('DELIVERY', 'Delivery Order'), ('INTERNAL', 'Internal Transfer'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting'), ('READY', 'Ready'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('partner_name', models.CharField(blank=True, help_text='Supplier (for receipts) or Customer (for deliveries)', max_length=200)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_created', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_to', to='inventory.location')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_from', to='inventory.location')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit / Code', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(help_text='e.g., units, kg, meters', max_length=50)),
                ('reorder_level', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Alert when total stock falls below this', max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory')),
            ],
            options={
                'ordering': ('sku',),
            },
        ),
        migrations.CreateModel(
            name='OperationLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('demanded_qty', models.DecimalField(decimal_places=4, help_text='How many units were expected/requested', max_digits=18)),
                ('done_qty', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='How many units were actually processed', max_digits=18)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryoperation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_lines', to='inventory.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_in', to='inventory.location')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='inventory.inventoryoperation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.product')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves_out', to='inventory.location')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockOnHand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_on_hand', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_on_hand', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_qty', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Reorder when stock falls below this', max_digits=18)),
                ('max_qty', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Reorder up to this quantity', max_digits=18)),
                ('reorder_qty', models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Quantity to reorder', max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='inventory.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inventoryoperation',
            index=models.Index(fields=['op_type', 'status'], name='inventory_i_op_type_b6c1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryoperation',
            index=models.Index(fields=['status', 'scheduled_date'], name='inventory_i_status_b8f797_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'name'], name='inventory_p_sku_b86f20_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['product', 'created_at'], name='inventory_s_product_cc37b2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['operation'], name='inventory_s_operati_f6fb21_idx'),
        ),
        migrations.AddIndex(
            model_name='stockonhand',
            index=models.Index(fields=['product', 'location'], name='inventory_s_product_0f57e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockonhand',
            unique_together={('product', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='reorderrule',
            unique_together={('product', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('warehouse', 'name')},
        ),
    ]
